In [141]:
#  https://www.cienciadedatos.net/documentos/py24-svm-python.html#:~:text=M%C3%A1quinas%20de%20Vector%20Soporte%20(Vector,campo%20de%20la%20ciencia%20computacional.
# https://pharos.sh/implementacion-de-svm-y-kernel-svm-con-scikit-learn-de-python/
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
from mlxtend.plotting import plot_decision_regions
# Preprocesado y modelado
# ==============================================================================
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.metrics import precision_score

# Configuración matplotlib
# ==============================================================================
plt.rcParams['image.cmap'] = "bwr"
#plt.rcParams['figure.dpi'] = "100"
plt.rcParams['savefig.bbox'] = "tight"
style.use('ggplot') or plt.style.use('ggplot')

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

In [155]:
#DATOS
d = pd.read_csv("CSV_Informacion_Categorizada/cont_sent_CR_PE_MX_UY.csv", sep="|")
df= d.rename(columns={'Unnamed: 0':'index'})
df.head(3)

index                                            Content Sentiment
0      0                 @NoilyMV yo soy totalmente puntual      NONE
1      1  @SandraCauffman Hola Sandrita. No le habia des...         P
2      2  Si andan haciendo eso mejor se quedaran callad...         N

In [156]:
df.shape

(3675, 3)

In [157]:
df['Sentiment'] = df.Sentiment.map({'N':0,'P':1})
df1= df.dropna()
df1

index                                            Content  Sentiment
1         1  @SandraCauffman Hola Sandrita. No le habia des...        1.0
2         2  Si andan haciendo eso mejor se quedaran callad...        0.0
3         3                     Que pereza quiero choco banano        0.0
4         4  @robertobrenes Bueno, no es tanto lo mayor com...        0.0
6         6  @doriamdiaz El de Halfon de Germinal se ve mor...        1.0
...     ...                                                ...        ...
3666    934  @CuadradoAndres @grazianopascale @adeladubra j...        1.0
3668    936  @Niaso01 @LuisSuarez9 @neymarjr El fútbol es h...        1.0
3669    937  #FelizDOMINGO que la paz de dios llene tu vida...        1.0
3672    940  A mi desayuno le hizo falta un alfajor podrida...        0.0
3673    941  Viste cuando necesitas que alguien te escuche ...        0.0

[2449 rows x 3 columns]

In [158]:
X= dataset.data
y= dataset.target

In [159]:
from sklearn.model_selection import train_test_split
#Separo los datos de "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [160]:
#Defino el algoritmo a utilizar
algoritmo = SVC(kernel = 'linear')
algoritmo.fit(X_train, y_train)
#prediccion
y_pred = algoritmo.predict(X_test)

In [161]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[43  1]
 [ 0 70]]


In [162]:
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average = "micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.9912280701754386


In [163]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)

SVC()

In [164]:
clf.predict([[2., 2.]])


array([1])

In [165]:
# get support vectors
clf.support_vectors_

# get indices of support vectors
clf.support_
# get number of support vectors for each class
clf.n_support_


array([1, 1], dtype=int32)

In [166]:
 
# reading csv file and extracting class column to y.
a = np.array(df)
y  = a[:,0] # classes having 0 and 1
  
# extracting two features
df = np.column_stack((df.Content,df.Sentiment))
  
# 569 samples and 2 features
df.shape 
  
print (df),(y)

[['@NoilyMV yo soy totalmente puntual' nan]
 ['@SandraCauffman Hola Sandrita. No le habia deseado un feliz dia de la madre, tarde pero seguro.¿ Sabe usted si Juno ha tomado mas fotos ?'
  1.0]
 ['Si andan haciendo eso mejor se quedaran calladitas jaja pero así se están quemando ellas mismas e insinuando que son unas metidas'
  0.0]
 ...
 ['A mi desayuno le hizo falta un alfajor podrida de las galletas de arroz'
  0.0]
 ['Viste cuando necesitas que alguien te escuche pero ese alguien no está? bueno'
  0.0]
 ['@cuervotinelli @candetinelli Mañana es mi primer sesión  , Vamo a tapar el tajo ...'
  nan]]


(None, array([0, 1, 2, ..., 940, 941, 942], dtype=object))

In [ ]:
#https://www.statdeveloper.com/maquinas-de-soporte-de-vectores-en-python/

In [ ]:
# https://aprendeia.com/maquinas-de-vectores-de-soporte-clasificacion-practica-con-python/